/* Generated by scripts/generate-sw.mjs — do not edit */
const CACHE_VERSION = "f24bf7bbdc";
const BASE_PATH = "/whereis-app";
const PRECACHE_URLS = [
  "/whereis-app/404.html",
  "/whereis-app/404/index.html",
  "/whereis-app/_next/static/CNWrX4aqHQLaBdZAnzqTW/_buildManifest.js",
  "/whereis-app/_next/static/CNWrX4aqHQLaBdZAnzqTW/_ssgManifest.js",
  "/whereis-app/_next/static/chunks/18.207d0ae99885e52c.js",
  "/whereis-app/_next/static/chunks/2200cc46-2d1891bd99606cb1.js",
  "/whereis-app/_next/static/chunks/290-d9ec5261c803bb02.js",
  "/whereis-app/_next/static/chunks/376-28537a33f1c31bfa.js",
  "/whereis-app/_next/static/chunks/713.ebd23059b1fc971d.js",
  "/whereis-app/_next/static/chunks/770.1d655bf49f9a344c.js",
  "/whereis-app/_next/static/chunks/780.f37b29289598bab5.js",
  "/whereis-app/_next/static/chunks/786.b3dd076093031b00.js",
  "/whereis-app/_next/static/chunks/788-8244f20e8e806bba.js",
  "/whereis-app/_next/static/chunks/945-691609ef329740d4.js",
  "/whereis-app/_next/static/chunks/995.1dfb2045650feb8b.js",
  "/whereis-app/_next/static/chunks/app/_not-found/page-c2bc4375e8b8eedd.js",
  "/whereis-app/_next/static/chunks/app/layout-96dcd54d4d498d4a.js",
  "/whereis-app/_next/static/chunks/app/page-9d532c39441c76a5.js",
  "/whereis-app/_next/static/chunks/app/qr/layout-0fc7b75e94ee9e2d.js",
  "/whereis-app/_next/static/chunks/app/qr/page-f0514fd00452306d.js",
  "/whereis-app/_next/static/chunks/app/search/layout-1a7b6418f88c7b97.js",
  "/whereis-app/_next/static/chunks/app/search/page-8328006e4f804c04.js",
  "/whereis-app/_next/static/chunks/app/space/[id]/page-2a355580021313ad.js",
  "/whereis-app/_next/static/chunks/framework-6e06c675866dc992.js",
  "/whereis-app/_next/static/chunks/main-app-420e2c06655a0822.js",
  "/whereis-app/_next/static/chunks/main-d211be51b365ab9a.js",
  "/whereis-app/_next/static/chunks/pages/_app-0c3037849002a4aa.js",
  "/whereis-app/_next/static/chunks/pages/_error-a647cd2c75dc4dc7.js",
  "/whereis-app/_next/static/chunks/polyfills-42372ed130431b0a.js",
  "/whereis-app/_next/static/chunks/webpack-fa5eca4da0c57235.js",
  "/whereis-app/_next/static/css/9aa71ecea02b3917.css",
  "/whereis-app/_next/static/media/19cfc7226ec3afaa-s.woff2",
  "/whereis-app/_next/static/media/21350d82a1f187e9-s.woff2",
  "/whereis-app/_next/static/media/8e9860b6e62d6359-s.woff2",
  "/whereis-app/_next/static/media/ba9851c3c22cd980-s.woff2",
  "/whereis-app/_next/static/media/c5fe6dc8356a8c31-s.woff2",
  "/whereis-app/_next/static/media/df0a9ae256c0569c-s.woff2",
  "/whereis-app/_next/static/media/e4af272ccee01ff0-s.p.woff2",
  "/whereis-app/apple-touch-icon.png",
  "/whereis-app/icon-512.png",
  "/whereis-app/icon.svg",
  "/whereis-app/index.html",
  "/whereis-app/manifest.webmanifest",
  "/whereis-app/qr/index.html",
  "/whereis-app/search/index.html",
  "/whereis-app/space/armari-1/index.html",
  "/whereis-app/space/armari-2/index.html",
  "/whereis-app/space/calaixera/index.html"
];

const STATIC_CACHE = "stashly-static-" + CACHE_VERSION;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(STATIC_CACHE)
      .then((cache) =>
        cache.addAll(
          PRECACHE_URLS.map((url) => new Request(url, { cache: "reload" })),
        ),
      )
      .then(() => self.skipWaiting())
      .catch(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter(
              (key) => key.startsWith("stashly-") && key !== STATIC_CACHE,
            )
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  const pathPrefix = BASE_PATH || "";

  if (url.pathname.includes("/_next/static/")) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (
    url.pathname.endsWith("/icon.svg") ||
    url.pathname.endsWith("/manifest.webmanifest") ||
    url.pathname.endsWith("/apple-touch-icon.png") ||
    url.pathname.endsWith("/icon-512.png")
  ) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(staleWhileRevalidatePage(request, pathPrefix));
  }
});

async function cacheFirst(request) {
  const cache = await caches.open(STATIC_CACHE);
  const cached = await cache.match(request);
  if (cached) return cached;

  const response = await fetch(request);
  if (response.ok) {
    cache.put(request, response.clone());
  }
  return response;
}

async function matchCachedPage(request, pathPrefix) {
  const cache = await caches.open(STATIC_CACHE);
  const url = new URL(request.url);

  const candidates = [request.url];

  if (url.pathname.endsWith("/")) {
    candidates.push(url.origin + url.pathname + "index.html");
  } else if (!url.pathname.endsWith(".html")) {
    candidates.push(url.origin + url.pathname + "/index.html");
  }

  if (pathPrefix && !url.pathname.startsWith(pathPrefix)) {
    return undefined;
  }

  for (const candidate of candidates) {
    const hit = await cache.match(candidate);
    if (hit) return hit;
  }

  return cache.match(request);
}

async function staleWhileRevalidatePage(request, pathPrefix) {
  const cache = await caches.open(STATIC_CACHE);
  const cached = await matchCachedPage(request, pathPrefix);

  const networkPromise = fetch(request)
    .then((response) => {
      if (response.ok) {
        cache.put(request, response.clone());
      }
      return response;
    })
    .catch(() => undefined);

  if (cached) {
    networkPromise.catch(() => {});
    return cached;
  }

  const network = await networkPromise;
  if (network) return network;

  throw new Error("Offline and no cached page");
}
