/* Generated by scripts/generate-sw.mjs — do not edit */
const CACHE_VERSION = "ff3bc735a2";
const BASE_PATH = "/whereis-app";
const PRECACHE_URLS = [
  "/whereis-app/404.html",
  "/whereis-app/404/index.html",
  "/whereis-app/_next/static/KPXXFcZtQ4uXeu0vml1fA/_buildManifest.js",
  "/whereis-app/_next/static/KPXXFcZtQ4uXeu0vml1fA/_ssgManifest.js",
  "/whereis-app/_next/static/chunks/135-1b8388dce837bc88.js",
  "/whereis-app/_next/static/chunks/275.960b6cff512d4e00.js",
  "/whereis-app/_next/static/chunks/295-bf79eef795e90af6.js",
  "/whereis-app/_next/static/chunks/369.0d3a88277f71069c.js",
  "/whereis-app/_next/static/chunks/425.42622b2d69bf8ebc.js",
  "/whereis-app/_next/static/chunks/588-3572a1c08aded2aa.js",
  "/whereis-app/_next/static/chunks/632-6ea8eec45a1770d1.js",
  "/whereis-app/_next/static/chunks/673.75cdd6af323bd160.js",
  "/whereis-app/_next/static/chunks/682.6ef1c4f905427943.js",
  "/whereis-app/_next/static/chunks/7d771d05-5bd70c7b17db77b6.js",
  "/whereis-app/_next/static/chunks/803.09cabff7a96d6393.js",
  "/whereis-app/_next/static/chunks/app/_not-found/page-e6d62aafb122ca29.js",
  "/whereis-app/_next/static/chunks/app/layout-b8dbda23afbea0b0.js",
  "/whereis-app/_next/static/chunks/app/page-d5b7fc48300fd399.js",
  "/whereis-app/_next/static/chunks/app/qr/layout-8fa4668b3c5501e0.js",
  "/whereis-app/_next/static/chunks/app/qr/page-19b75dcc3e5f816a.js",
  "/whereis-app/_next/static/chunks/app/search/layout-6d059f074b8a10a3.js",
  "/whereis-app/_next/static/chunks/app/search/page-2cfdc86db37d53bb.js",
  "/whereis-app/_next/static/chunks/app/space/[id]/page-529ea5ea1310a780.js",
  "/whereis-app/_next/static/chunks/framework-6e06c675866dc992.js",
  "/whereis-app/_next/static/chunks/main-app-0e6ef7630c30f47d.js",
  "/whereis-app/_next/static/chunks/main-f76f6b91bb6ec220.js",
  "/whereis-app/_next/static/chunks/pages/_app-6b6d838185df6281.js",
  "/whereis-app/_next/static/chunks/pages/_error-afbb8b192815ec9b.js",
  "/whereis-app/_next/static/chunks/polyfills-42372ed130431b0a.js",
  "/whereis-app/_next/static/chunks/webpack-1f55e5c456f7eef8.js",
  "/whereis-app/_next/static/css/660f14684dfe7a01.css",
  "/whereis-app/_next/static/media/19cfc7226ec3afaa-s.woff2",
  "/whereis-app/_next/static/media/21350d82a1f187e9-s.woff2",
  "/whereis-app/_next/static/media/8e9860b6e62d6359-s.woff2",
  "/whereis-app/_next/static/media/ba9851c3c22cd980-s.woff2",
  "/whereis-app/_next/static/media/c5fe6dc8356a8c31-s.woff2",
  "/whereis-app/_next/static/media/df0a9ae256c0569c-s.woff2",
  "/whereis-app/_next/static/media/e4af272ccee01ff0-s.p.woff2",
  "/whereis-app/apple-touch-icon.png",
  "/whereis-app/icon-512.png",
  "/whereis-app/icon.svg",
  "/whereis-app/index.html",
  "/whereis-app/manifest.webmanifest",
  "/whereis-app/qr/index.html",
  "/whereis-app/search/index.html",
  "/whereis-app/space/armari-1/index.html",
  "/whereis-app/space/armari-2/index.html",
  "/whereis-app/space/calaixera/index.html"
];

const STATIC_CACHE = "stashly-static-" + CACHE_VERSION;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(STATIC_CACHE)
      .then((cache) =>
        cache.addAll(
          PRECACHE_URLS.map((url) => new Request(url, { cache: "reload" })),
        ),
      )
      .then(() => self.skipWaiting())
      .catch(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter(
              (key) => key.startsWith("stashly-") && key !== STATIC_CACHE,
            )
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  const pathPrefix = BASE_PATH || "";

  if (url.pathname.includes("/_next/static/")) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (
    url.pathname.endsWith("/icon.svg") ||
    url.pathname.endsWith("/manifest.webmanifest") ||
    url.pathname.endsWith("/apple-touch-icon.png") ||
    url.pathname.endsWith("/icon-512.png")
  ) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(staleWhileRevalidatePage(request, pathPrefix));
  }
});

async function cacheFirst(request) {
  const cache = await caches.open(STATIC_CACHE);
  const cached = await cache.match(request);
  if (cached) return cached;

  const response = await fetch(request);
  if (response.ok) {
    cache.put(request, response.clone());
  }
  return response;
}

async function matchCachedPage(request, pathPrefix) {
  const cache = await caches.open(STATIC_CACHE);
  const url = new URL(request.url);

  const candidates = [request.url];

  if (url.pathname.endsWith("/")) {
    candidates.push(url.origin + url.pathname + "index.html");
  } else if (!url.pathname.endsWith(".html")) {
    candidates.push(url.origin + url.pathname + "/index.html");
  }

  if (pathPrefix && !url.pathname.startsWith(pathPrefix)) {
    return undefined;
  }

  for (const candidate of candidates) {
    const hit = await cache.match(candidate);
    if (hit) return hit;
  }

  return cache.match(request);
}

async function staleWhileRevalidatePage(request, pathPrefix) {
  const cache = await caches.open(STATIC_CACHE);
  const cached = await matchCachedPage(request, pathPrefix);

  const networkPromise = fetch(request)
    .then((response) => {
      if (response.ok) {
        cache.put(request, response.clone());
      }
      return response;
    })
    .catch(() => undefined);

  if (cached) {
    networkPromise.catch(() => {});
    return cached;
  }

  const network = await networkPromise;
  if (network) return network;

  throw new Error("Offline and no cached page");
}
