/**
 * Post-build: generate out/sw.js with a precache manifest from the static export.
 * Run after `next build` (see package.json).
 */
import crypto from "crypto";
import fs from "fs";
import path from "path";

const OUT_DIR = "out";
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

function walk(dir, files = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, files);
    } else {
      files.push(full);
    }
  }
  return files;
}

function shouldPrecache(relativePath) {
  if (relativePath.endsWith(".html")) return true;
  if (relativePath.includes("_next/static/")) return true;
  if (
    relativePath === "icon.svg" ||
    relativePath === "manifest.webmanifest" ||
    relativePath === "apple-touch-icon.png" ||
    relativePath === "icon-512.png"
  ) {
    return true;
  }
  return false;
}

if (!fs.existsSync(OUT_DIR)) {
  console.error("generate-sw: out/ not found — run next build first");
  process.exit(1);
}

const precachePaths = walk(OUT_DIR)
  .map((file) => path.relative(OUT_DIR, file).replace(/\\/g, "/"))
  .filter(shouldPrecache)
  .sort()
  .map((rel) => `${basePath}/${rel}`);

const version = crypto
  .createHash("md5")
  .update(precachePaths.join("\n"))
  .digest("hex")
  .slice(0, 10);

const swSource = `/* Generated by scripts/generate-sw.mjs — do not edit */
const CACHE_VERSION = "${version}";
const BASE_PATH = ${JSON.stringify(basePath)};
const PRECACHE_URLS = ${JSON.stringify(precachePaths, null, 2)};

const STATIC_CACHE = "stashly-static-" + CACHE_VERSION;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(STATIC_CACHE)
      .then((cache) =>
        cache.addAll(
          PRECACHE_URLS.map((url) => new Request(url, { cache: "reload" })),
        ),
      )
      .then(() => self.skipWaiting())
      .catch(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter(
              (key) => key.startsWith("stashly-") && key !== STATIC_CACHE,
            )
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  const pathPrefix = BASE_PATH || "";

  if (url.pathname.includes("/_next/static/")) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (
    url.pathname.endsWith("/icon.svg") ||
    url.pathname.endsWith("/manifest.webmanifest") ||
    url.pathname.endsWith("/apple-touch-icon.png") ||
    url.pathname.endsWith("/icon-512.png")
  ) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(staleWhileRevalidatePage(request, pathPrefix));
  }
});

async function cacheFirst(request) {
  const cache = await caches.open(STATIC_CACHE);
  const cached = await cache.match(request);
  if (cached) return cached;

  const response = await fetch(request);
  if (response.ok) {
    cache.put(request, response.clone());
  }
  return response;
}

async function matchCachedPage(request, pathPrefix) {
  const cache = await caches.open(STATIC_CACHE);
  const url = new URL(request.url);

  const candidates = [request.url];

  if (url.pathname.endsWith("/")) {
    candidates.push(url.origin + url.pathname + "index.html");
  } else if (!url.pathname.endsWith(".html")) {
    candidates.push(url.origin + url.pathname + "/index.html");
  }

  if (pathPrefix && !url.pathname.startsWith(pathPrefix)) {
    return undefined;
  }

  for (const candidate of candidates) {
    const hit = await cache.match(candidate);
    if (hit) return hit;
  }

  return cache.match(request);
}

async function staleWhileRevalidatePage(request, pathPrefix) {
  const cache = await caches.open(STATIC_CACHE);
  const cached = await matchCachedPage(request, pathPrefix);

  const networkPromise = fetch(request)
    .then((response) => {
      if (response.ok) {
        cache.put(request, response.clone());
      }
      return response;
    })
    .catch(() => undefined);

  if (cached) {
    networkPromise.catch(() => {});
    return cached;
  }

  const network = await networkPromise;
  if (network) return network;

  throw new Error("Offline and no cached page");
}
`;

fs.writeFileSync(path.join(OUT_DIR, "sw.js"), swSource);
console.log(
  `generate-sw: ${precachePaths.length} URLs precached (version ${version})`,
);
